# -----------------------------------------------------------------------------
# Docker IMAGE congressy/cgsy
# docker build --rm -t cgsy .
# docker tag catalog <repo_url>/cgsy:<tag>
# -----------------------------------------------------------------------------
FROM python:3.7-slim

# Celery does not work with root unless you force it
ENV C_FORCE_ROOT true

LABEL cgsy.image.name="notification-service"

# Install packages needed to run your application (not build deps):
#   mime-support -- for mime types when serving static files
#   postgresql-client -- for running database commands
# We need to recreate the /usr/share/man/man{1..8} directories first because
# they were clobbered by a parent image.
RUN set -ex \
    && RUN_DEPS=" \
        nano \
        mime-support \
        locales \
        libpcre3 \
        build-essential \
        libxml2 \
    " \
    && seq 1 8 | xargs -I{} mkdir -p /usr/share/man/man{} \
    && apt-get update && apt-get install -y --no-install-recommends $RUN_DEPS \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Locales
ENV LC_ALL=pt_BR.UTF-8 LANG=pt_BR.UTF-8

RUN localedef -i pt_BR -c -f UTF-8 -A /usr/share/locale/locale.alias pt_BR.UTF-8

# -----------------------------------------------------------------------------
COPY ./requirements.txt /requirements.txt
COPY ./requirements.dev.txt /requirements.dev.txt

# Install build deps, then run `pip install`, then remove unneeded build deps all in a single step.
# Correct the path to your production requirements file, if needed.
RUN set -ex \
    && BUILD_DEPS=" \
        libtiff5-dev \
        libjpeg62-turbo-dev \
        zlib1g-dev \
        libfreetype6-dev \
        liblcms2-dev \
        libwebp-dev \
        libxml2-dev \
        libxslt-dev \
        python-dev \
        libpq-dev \
    " \
    && seq 1 8 | xargs -I{} mkdir -p /usr/share/man/man{} \
    && apt-get update && apt-get install -y --no-install-recommends $BUILD_DEPS \
    && pip3 install -U pip \
    # Exclusive packages for production environment.
    && pip3 install --no-cache-dir -r /requirements.dev.txt \
    # Django packs, after pip to avoid unnecessary download
    && pip3 install --no-cache-dir -U \
        gunicorn==20.0.4 \
    && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false $BUILD_DEPS \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# -----------------------------------------------------------------------------
# Setup configuration files
COPY ./conf /app_conf

# -----------------------------------------------------------------------------
WORKDIR /code/

# -----------------------------------------------------------------------------
COPY ./. ./.

RUN chmod +x /app_conf/services/app/container-entry.sh \
             /app_conf/services/celery/container-entry.sh

# server will listen on this port
EXPOSE 8000
