version: '3.5'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: notification-serv-rabbitmq
    networks:
      - rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_ERLANG_COOKIE=rabbitmqservice
    ports:
      - "15672:15672"
      - "5672:5672"

  flower:
    image: hugoseabra19/docker-celery-flower
    container_name: notification-serv-flower
    environment:
      - CELERY_BROKER_URL=amqp://admin:admin@rabbitmq:5672/
      - FLOWER_PORT=5555
    ports:
      - 5555:5555
    networks:
      - rabbitmq

networks:
  rabbitmq:
    name: local_rabbitmq
