# Generated by Django 3.0.7 on 2020-06-24 20:56

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('broker_type', models.CharField(max_length=255, verbose_name='broker type')),
                ('broker_id', models.IntegerField(db_index=True, unique=True, verbose_name='broker id')),
                ('device_type', models.CharField(max_length=255, verbose_name='device type')),
                ('model', models.CharField(max_length=255, verbose_name='model')),
                ('unique_id', models.IntegerField(db_index=True, unique=True, verbose_name='unique id')),
                ('brand', models.CharField(max_length=255, verbose_name='brand')),
                ('os_build_number', models.IntegerField(db_index=True, unique=True, verbose_name='os build number')),
                ('os_version', models.IntegerField(db_index=True, unique=True, verbose_name='os version')),
                ('os_bundle_id', models.IntegerField(db_index=True, unique=True, verbose_name='os bundle id')),
                ('os_readable_version', models.IntegerField(db_index=True, unique=True, verbose_name='os readable version')),
                ('android_fringerprint', models.CharField(blank=True, max_length=255, null=True, verbose_name='android fingerprint')),
                ('android_install_time', models.CharField(blank=True, max_length=255, null=True, verbose_name='android install time')),
                ('android_bootloader', models.CharField(blank=True, max_length=255, null=True, verbose_name='android bootloader')),
                ('ios_device_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='ios device token')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Device',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('alias', models.CharField(max_length=255, verbose_name='alias')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Group',
            },
        ),
        migrations.CreateModel(
            name='Namespace',
            fields=[
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('external_id', models.IntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='external id')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Namespace',
                'verbose_name_plural': 'Namespace',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('user', models.CharField(max_length=255, verbose_name='user')),
                ('groups', models.ManyToManyField(to='notification.Group')),
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscriber',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('type', models.CharField(max_length=255, verbose_name='type')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('delivered', 'Delivered'), ('retry', 'Retry'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], max_length=255, verbose_name='status')),
                ('text', models.CharField(max_length=255, verbose_name='text')),
                ('extra_data', jsonfield.fields.JSONField(blank=True, null=True)),
                ('device', models.ForeignKey(db_column='unique_id', on_delete=django.db.models.deletion.DO_NOTHING, to='notification.Device')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notification',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='namespace',
            field=models.ForeignKey(blank=True, db_column='namespace', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='notification.Namespace'),
        ),
        migrations.AddField(
            model_name='device',
            name='subscriber',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.DO_NOTHING, to='notification.Subscriber'),
        ),
    ]
