# Generated by Django 3.0.7 on 2020-06-24 14:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Namespace',
            fields=[
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('external_id', models.IntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='external id')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Namespace',
                'verbose_name_plural': 'Namespace',
            },
        ),
    ]
